### ISSUE TITLE
Cannot run from CLI, as 'buildnumgen' cannot be found

### ISSUE THREAD

**Issue by RaddishIoW** [prantlf/build-number-generator#4]
`buildnumgen` cannot be run from the command line, as the file in the `bin` dir is now named `buildnumgen.js` and not `buildnumgen` as in v.1.0.0.

**Comment by prantlf** [comment]
Oh, you're right! When I included support for ES modules, made a mistake when renaming the files to `cjs` and `.mjs`. Installation of the command-line script stopped working. I'm fixing it.

The extension of the source file in `bin` shouldn't be known to users. NPM will create a platform-specific script/batch file in `node_modules/.bin` again, once I fix it.

Thanks for reporting this!

**Comment by prantlf** [comment]
I fixed this in [2.0.3](https://github.com/prantlf/build-number-generator/releases/tag/v2.0.3).

Requiring `build-number-generator` in CJS modules works again.
Running the script `buildnumgen` using `npx`, from `package.json` or from `PATH` including `node_modules/.bin` works again.

**Comment by prantlf** [comment]
And thanks for noticing the not exported TypeScript types! The [2.4.0](https://github.com/prantlf/build-number-generator/releases/tag/v2.0.4) finally fixes all the issues.
